function plot_all_oscillators(times, x, dtheta, drives, sigma)
% plot_salam_cpg(times, x, dtheta, drives)
%
% Plot the oscillator outputs and instantaneous frequencies of a model of
% the salamander CPG, as generated by the function 'salam_cpg_osc'.
%
% Inputs:
%   times   A vector of times defining the integration steps (e.g. 0:0.01:10)
%   x       A matrix of the oscillators' outputs (rows and columns as for r)
%   dtheta  A matrix of the oscillators' instantaneous frequencies, in rad/s
%   drives  A vector of same size as times, giving the drive level for the
%           corresponding time. Can also be a scalar (for constant drive).

  % Make sure we have a column vector of drives
  if length(drives) == 1
    drives = ones(length(times), 1) * drives;
  else
    drives = drives(:); % indexing with (:) ensures we have a column vector
  end

  nrsubplots = 4;
  
  % Make figure with given title
  FigHandle = figure('name', 'Salamander CPG output');
  clf;
  
  % Colors from Tango palette
  blue = [0.16 0.34 0.59];
  green = [0.38 0.71 0.055];
  violett = [153/255 0 204/255];
  orange = [230/255 138/255 0];
  n_segments = 16;                     % 8 axial segments
  girdles = [1 5];                    % Forelimbs project to segments 1-4, hind limbs to segments 5-end
  
  % Indices for trunk and tail oscillators on left side
  trunk = 1:girdles(2) - 1;
  tail = girdles(2):n_segments;
  

  % First subplot: axial oscillations
  % Using two rows to make it twice the height of the other plots
  subplot(nrsubplots, 1, [1 2]);

  
  % Plotting trunk and tail oscillations separately, to have different colors:
  hold on;
  p1 = plot(times, x(:, 1) +8*3, 'color', blue, 'linewidth', 2);
  p2 = plot(times, x(:, 1+8) +8*3, 'color', violett, 'linewidth', 2);
  plot(times, x(:, 2) +7*3, 'color', blue, 'linewidth', 2);
  plot(times, x(:, 2+8) +7*3, 'color', violett, 'linewidth', 2);
  plot(times, x(:, 3) +6*3, 'color', blue, 'linewidth', 2);
  plot(times, x(:, 3+8) +6*3, 'color', violett, 'linewidth', 2);
  plot(times, x(:, 4) +5*3, 'color', blue, 'linewidth', 2);
  plot(times, x(:, 4+8) +5*3, 'color', violett, 'linewidth', 2);
  p3 = plot(times, x(:, 5) + 4*3, 'color', green, 'linewidth', 2);
  p4 = plot(times, x(:, 5+8) + 4*3, 'color', orange, 'linewidth', 2);
  plot(times, x(:, 6) + 3*3, 'color', green, 'linewidth', 2);
  plot(times, x(:, 6+8) + 3*3, 'color', orange, 'linewidth', 2);
  plot(times, x(:, 7) + 2*3, 'color', green, 'linewidth', 2);
  plot(times, x(:, 7+8) + 2*3, 'color', orange, 'linewidth', 2);
  plot(times, x(:, 8) +3, 'color', green, 'linewidth', 2);
  plot(times, x(:, 8+8) + 3, 'color', orange, 'linewidth', 2);
  hold off;
  set(gca,'ytick',[], 'xtick', []);
  ylabel('x Body');
  ylim([0.5 30]);
  legend([p1 p2 p3 p4], 'Upper left axial oscillators','Upper right axial oscillators','Lower left axial oscillators','Lower right axial oscillators');


  % Limb oscillations
  subplot(nrsubplots, 1, 3);
  hold on;
  LF = 2 * n_segments + 1; % left forelimb
  LH = 2 * n_segments + 3; % left hind limb
  plot(times, x(:, 17) + 6, 'color', blue, 'linewidth', 2);
  plot(times, x(:, 18) + 6, 'color', violett, 'linewidth', 2);
  plot(times, x(:, 19) + 2, 'color', green, 'linewidth', 2)  
  plot(times, x(:, 20) + 2, 'color', orange, 'linewidth', 2);
  legend('Upper left limb','Upper right limb','Lower left limb','Lower right limb');
  hold off;

  set(gca,'ytick',[], 'xtick', []);
  ylabel('x Limb');
  ylim([0.5 10]);
  
  
  % Drive
  subplot(nrsubplots, 1, 4);
  plot(times, drives, 'color', 'black');
  ylabel('Drive d');  
  xlabel('Time [s]');
  
  
  print -dpng salam_all_cpg.png
  
end
